spring:
  datasource:
    url: jdbc:h2:mem:testdb # DB 접속 URL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha